"""Append new rows to hekhalot-kundalini-vision-timeline.csv."""
import csv, os

PATH = '/Users/paulbloch/Documents/github/Messiah-Complex/static/sources/comparative-myths/hekhalot-kundalini-vision-timeline.csv'

NEW_ROWS = [
    # ── Mesopotamian / Parpola entries ──────────────────────────────────────────
    {
        "Date_Label": "c. 4000–3000 BCE",
        "Date_Sort": "-4000",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Mesopotamian (Sumerian)",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Sumerian Sacred Tree and World Pillar – Eridu Cosmogony (Kigkanu)",
        "Person_Visionary": "Anonymous Sumerian tradition",
        "Location": "Eridu / Nippur (Sumer)",
        "Source_Text": "CT 16 46:183ff.; Widengren 'The King and the Tree of Life' (Uppsala 1951)",
        "Description": "Black kigkanu tree in Eridu: 'created in a holy place; its sheen is pure lapis lazuli drawing from the Apsu'; the World Pillar (Dur-an-ki = Bond of Heaven and Earth) as the cosmic axis; Eridu as navel of the world; apkallu sages tend the tree; tree links heaven, earth, and underworld. Earliest textual record of a named sacred tree in any tradition.",
        "Key_Motifs": "World tree; cosmic axis; lapis lazuli; apkallu sages; underworld waters; Apsu; navel of world",
        "Parallel_Systems": "Hekhalot (heavenly palaces rooted in same cosmic-axis theology); Kundalini (spine/sushumna as cosmic axis – Tier C); OT Visions (Jacob's ladder; Ezekiel kavod above firmament)",
        "Scholarly_Source": "Parpola, 'The Assyrian Tree of Life' JNES 52/3 (1993) pp. 163–164; Widengren (1951); Lambert, BSOAS 48 (1985)",
        "Evidence_Tier": "B",
        "Notes": "Earliest textual reference to a named sacred tree in Mesopotamia; prototype for all subsequent Mesopotamian sacred tree iconography",
    },
    {
        "Date_Label": "c. 2500–1243 BCE",
        "Date_Sort": "-2500",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Mesopotamian (Assyrian/Babylonian)",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Pre-Assyrian Sacred Tree – Triadic Nodes and Flanking Figures Across the Near Eastern Oikumene",
        "Person_Visionary": "Neo-Sumerian through Mitannian traditions",
        "Location": "Mesopotamia (Assur; Nippur; Babylon) → Egypt → Greece → Indus",
        "Source_Text": "Cylinder seals; Mitannian seals 14th c. BCE; Kepinski 'L'Arbre stylisé en Asie occidentale au 2e millénaire' (Paris 1982)",
        "Description": "Stylized tree motif from 4th millennium BCE; by the 2nd millennium found throughout the Near Eastern oikumene including Egypt, Greece, and the Indus Valley. Characterized by triadic trunk, palmette crown, flanking animals (ibexes, goats, eagles). Harappan forms show Proto-Elamite and Akkadian influence. Earliest Greek examples (15th c. BCE) are 'pronouncedly Babylonian' (Parpola). Egyptian examples arrived via Hyksos from 16th c. BCE.",
        "Key_Motifs": "Stylized tree; triadic trunk nodes; flanking animals; palmette crown; spread to Egypt / Greece / Indus",
        "Parallel_Systems": "Hekhalot (angelic flanking figures at each hall); Kundalini (three-columned trunk = ida/pingala/sushumna – Tier C); OT Visions (Asherah; Eden tree)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 161–163; Kepinski (1982); Danthine 'Le Palmier-dattier et les arbres sacrés' (Paris 1937)",
        "Evidence_Tier": "A",
        "Notes": "By the Middle Bronze Age the sacred tree is the dominant religious icon of the entire Near East; spread confirmed to the Indus Valley predating Vedic India",
    },
    {
        "Date_Label": "c. 1243 BCE",
        "Date_Sort": "-1243",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Neo-Assyrian Imperial",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Neo-Assyrian Sacred Tree Diagram – Ten-Node Sefirotic Prototype (Tukulti-Ninurta I)",
        "Person_Visionary": "Tukulti-Ninurta I (king); Assyrian court scholars",
        "Location": "Kar-Tukulti-Ninurta / Assur (Assyria)",
        "Source_Text": "Seal impression KAJ 144 (dated to Tukulti-Ninurta I eponymy); wall paintings of Kar-Tukulti-Ninurta; Parpola JNES 52/3 (1993)",
        "Description": "The canonical Late Assyrian Tree first appears under Tukulti-Ninurta I: trunk with three triadic nodes (each with two flanking circles = 3×3 = 9 nodes plus crown = 10 total); winged disk (Assur = En Sof) hovering above; flanking king or apkallu figures; pomegranate/pinecone garland symbolizing 'unity in multiplicity'; tripartite trunk = three pillars of Kabbalah. Parpola demonstrates this diagram is structurally identical to the Kabbalistic Sefirotic Tree when Mesopotamian gods replace the Sefirot.",
        "Key_Motifs": "Three triadic nodes; winged disk above (En Sof / Assur); three-columned trunk; pomegranate garland; 10-point structure; flanking figures; tripartite pillars",
        "Parallel_Systems": "Hekhalot (same ten divine attributes structure the angelic hierarchy); Kabbalah (Sefirotic Tree = direct adaptation – Parpola's main thesis); Kundalini (10-node vs. 7-chakra structural comparison – Tier C)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 163–176 and fig. 7 (reconstructed Tree); Beran ZA 47–52; Moortgat ZA 48 (1944)",
        "Evidence_Tier": "A",
        "Notes": "CRITICAL FINDING (Parpola): mystic numbers of Mesopotamian gods (Anu=1; Ea=60; Sin=30; Samas=20; Marduk=50; Ishtar=15; Ninurta/Nabu=50; Adad=10; Nergal=14) map exactly onto Sefirotic positions — his proof of direct Mesopotamian→Kabbalah transmission",
    },
    {
        "Date_Label": "c. 1243 BCE",
        "Date_Sort": "-1242",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Neo-Assyrian Esoteric",
        "Entry_Type": "Comparative Note",
        "Title_Event": "Parpola's Mapping: Mesopotamian Gods → Kabbalistic Sefirot (JNES 1993 fig. 7)",
        "Person_Visionary": "Simo Parpola (1993 reconstruction)",
        "Location": "Assur / Nippur / Babylonia",
        "Source_Text": "Parpola JNES 52/3 (1993) pp. 176–182 and fig. 7; Tallqvist 'Akkadische Götterepitheta' (Helsinki 1938)",
        "Description": "Parpola places Mesopotamian gods in the ten Sefirotic positions: KETER=Anu (Heaven; #1; father of gods); HOKHMAH=Ea/Enki (wisdom; #60; 'sage of gods; lord of secrets'); BINAH=Sin/Moon (deep intellect; #30; 'whose counsel nobody perceives'); HESED=Marduk (merciful father; #50); DIN/GEVURAH=Shamash (divine judge; #20); TIFERET=Ishtar/Venus (beauty/love; #15); NETZAH=Ninurta/Nabu (victory warrior; #50/10); HOD=Adad/Girru (storm splendor; #10); YESOD=Nergal (strength/foundation; #14); MALKHUT=the king (distributor of the divine stream). Biblical evidence: 1 Chr 29:11 lists gedullah-gevurah-tiferet-nezah-hod in exact Sefirotic diagram order.",
        "Key_Motifs": "Keter=Anu; Hokhmah=Ea; Binah=Sin; Hesed=Marduk; Gevurah=Shamash; Tiferet=Ishtar; Netzah=Ninurta/Nabu; Hod=Adad; Yesod=Nergal; Malkhut=king",
        "Parallel_Systems": "Hekhalot (angelic names ending in -EL mirror Mesopotamian divine names in same positions); OT Visions (1 Chr 29:11 David's blessing enumerates five Sefirot in order); Kabbalah (direct ancestral model)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 176–182; Scholem 'Origins of the Kabbalah' (1987); Idel 'Kabbalah: New Perspectives' (1988)",
        "Evidence_Tier": "A",
        "Notes": "Parpola's reconstruction is the strongest published case for Mesopotamian origin of the Sefirot; 1 Chr 29:11 Sefirotic sequence = biblical-level evidence (Tier A)",
    },
    {
        "Date_Label": "c. 1200–600 BCE",
        "Date_Sort": "-1200",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Mesopotamian (Babylonian)",
        "Entry_Type": "Text",
        "Title_Event": "Enuma Elish – Sacred Tree Cosmogony as Encoded Mathematical Theogony",
        "Person_Visionary": "Anonymous Babylonian scholars; canonical version c. 1200 BCE",
        "Location": "Babylon / Nippur",
        "Source_Text": "Enuma Elish Tablets I–VII; Lambert & Millard ed. (1969); Parpola JNES 52/3 (1993) pp. 190–191",
        "Description": "Parpola demonstrates Enuma Elish encodes the Tree diagram: Apsu + Mummu + Tiamat = primordial undifferentiated unity (En Sof equivalent); Lahmu/Lahamu = binary system of oppositions; Anshar = Assur = the Infinite Light; Anu emanated as Anshar's 'mirror' (not created, but reflected); mystic numbers of gods embedded in narrative sequence. The theogony is a mathematical process encoded in mythological language. Parpola explicitly compares Apsu-Tiamat to Shiva-Shakti in primordial union: 'the metaphysical propositions of Tantra are stated in very similar terms.'",
        "Key_Motifs": "Mathematical cosmogony; binary oppositions; emanation not creation; primordial zero; Anshar as Endless Light; Apsu-Tiamat = Shiva-Shakti",
        "Parallel_Systems": "Hekhalot (same divine council structure); Kabbalah (En Sof parallel to Anshar); Kundalini (Apsu-Tiamat = Shiva-Shakti primordial undivided consciousness – Parpola's own explicit comparison; Tier B)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 190–191 and nn. 109–116; Wallis 'Neoplatonism' (1972) pp. 47–72",
        "Evidence_Tier": "B",
        "Notes": "Parpola's mathematical reading is speculative but internally consistent; the Tantra comparison is Parpola's own (not a New Age overlay); mystic number sequences are independently verifiable (Tier A for numbers; Tier B for cosmogonic interpretation)",
    },
    {
        "Date_Label": "c. 2100–600 BCE",
        "Date_Sort": "-1800",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Mesopotamian (Babylonian)",
        "Entry_Type": "Text",
        "Title_Event": "Gilgamesh Epic – Tree Diagram as Structural Map of Mystical Ascent (Parpola)",
        "Person_Visionary": "Anonymous; canonical version by Sin-leqi-unninni c. 1200 BCE",
        "Location": "Uruk / Nippur / Nineveh",
        "Source_Text": "Standard Babylonian Gilgamesh Epic (George, OUP 2003); Parpola JNES 52/3 (1993) pp. 192–195",
        "Description": "Parpola argues the 12-tablet Gilgamesh Epic is structured after the Sefirotic Tree (each tablet = one node); Tablets I–VIII = soul development through lower Sefirot; Tablet IX = passage through Daat (void before divine union; the dark-mountain passage); Tablets X–XI = cosmic knowledge journey; Tablet XII = Crown (Anu) = mystical reunion with Enkidu and secrets of the afterlife. The Epic's hidden 'secret' = the same 'secret of the world' later revealed in Hekhalot Rabbati. The 'walls of Uruk' = the Tree as structural diagram; the 'lapis lazuli tablet' = the hidden esoteric key.",
        "Key_Motifs": "12 tablets = 12 Sefirotic positions; Tablet IX = Daat void; lapis lazuli tablet; secret of immortality; gates and walls; passage through darkness",
        "Parallel_Systems": "Hekhalot (Hekhalot Rabbati = same 'ascent to heaven' secret Gilgamesh obtains); OT Visions (Daniel's cosmic journey; Ezekiel's ascent); Kundalini (journey through dangers = kundalini obstacles at each chakra – Tier C)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 192–195; George 'The Babylonian Gilgamesh Epic' (OUP 2003); Idel 'Kabbalah: New Perspectives' (1988) pp. 88–94",
        "Evidence_Tier": "B",
        "Notes": "Parpola's structural reading is a minority scholarly view; his linkage of Gilgamesh's 'secret' to Hekhalot's 'secret of the world' is his most important insight connecting Mesopotamian narrative to Jewish mystical practice",
    },
    {
        "Date_Label": "c. 2600–1200 BCE",
        "Date_Sort": "-2600",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Mesopotamian (Sumerian/Akkadian)",
        "Entry_Type": "Text",
        "Title_Event": "Etana Myth – Eagle Ascent as Earliest Recorded Heavenly Ascent Narrative",
        "Person_Visionary": "Etana (mythological king of Kish)",
        "Location": "Kish / Nippur (Sumer / Akkad)",
        "Source_Text": "Etana Myth (Kinnier Wilson, 'The Legend of Etana' 1985); Parpola JNES 52/3 (1993) pp. 195–200",
        "Description": "Etana ascends to heaven on the back of an eagle through seven heaven levels to retrieve the 'plant of birth'; earth shrinks to a point as they ascend. Parpola links this to the Merkabah tradition: eagle = divine chariot; plant of birth = the Tree; ascent for the birth-secret = Hekhalot ascent for divine secrets. In Ishtar's vision within the myth the eagle is described as a beautiful winged man – identified by Parpola with the Sefirah Tiferet/Ishtar.",
        "Key_Motifs": "Eagle as chariot; seven-level ascent; earth shrinking below; divine secret retrieval; plant of birth; Ishtar vision of the eagle-man",
        "Parallel_Systems": "Hekhalot (eagle chariot = Merkabah; Etana's ascent = prototype of Jewish heavenly ascent – Tier B); OT Visions (Elijah's chariot; Ezekiel's Merkabah); Kundalini (eagle = Garuda vehicle of Vishnu in kundalini iconography – Tier C)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 195–200; Kinnier Wilson 'The Legend of Etana' (1985)",
        "Evidence_Tier": "B",
        "Notes": "Etana myth = earliest known narrative of heavenly ascent (c. 2600 BCE tradition); eagle-vehicle is pan-Eurasian (Garuda; Zeus's eagle; Horus-falcon; Simurgh); Parpola proves the Ishtar-Tiferet identification within the myth itself",
    },
    {
        "Date_Label": "c. 900–612 BCE",
        "Date_Sort": "-900",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Neo-Assyrian Imperial",
        "Entry_Type": "Transmission",
        "Title_Event": "Neo-Assyrian Tree Doctrine Spreads to Vassal Territories – Six Post-Assyrian Daughter-Systems",
        "Person_Visionary": "Assyrian court scholars (ummanu); scribes; prophets",
        "Location": "Nineveh / Calah / Dur-Sharrukin → vassal territories (Judah; Persia; Greece; Babylonia)",
        "Source_Text": "Parpola JNES 52/3 (1993) pp. 189–190; SAA 3; 1 Chr 29:11 (biblical evidence)",
        "Description": "After the fall of the Assyrian empire (612 BCE) the Tree's religious ideas spread to former vassals; Parpola identifies six 'new religions' emerging simultaneously after Assyrian collapse: (1) Zoroastrianism (Persia); (2) Pythagoreanism (Greece); (3) Orphism (Greece); (4) Platonism (Greece); (5) Jewish monotheism (Babylonian exile); (6) Kabbalah via Babylonian rabbinical schools. Neoplatonists Plotinus and Porphyry themselves said Pythagorean and Platonic teachings came from 'the East.' Biblical passage 1 Chr 29:11 enumerates five Sefirotic names in exact Sefirotic diagram order — biblical-level documentation of the diagram's absorption into Hebrew theology.",
        "Key_Motifs": "Post-Assyrian transmission; six daughter-traditions; Babylonian exile as conduit; oral tradition preserved; Achaemenid absorption of Assyrian symbolism",
        "Parallel_Systems": "Hekhalot (Babylonian rabbinical schools = direct conduit for Merkabah mysticism); Kabbalah (transmitted via Aaron ben Samuel of Babylonia to Italy, 870 CE); Zoroastrianism (dualist Tree pillars); Greek philosophy (Pythagorean sacred numbers = Mesopotamian divine numbers)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 189–190; Scholem 'Major Trends in Jewish Mysticism' (1941); Burkert 'The Orientalizing Revolution' (1992)",
        "Evidence_Tier": "B",
        "Notes": "Six philosophical-religious systems simultaneously emerging after Assyrian collapse is historically striking; Babylonian exile → Kabbalah is Tier A; Pythagorean-Platonic connection is Tier B; all six systems share a ten-attribute divine structure",
    },
    # ── Egyptian entries ──────────────────────────────────────────────────────────
    {
        "Date_Label": "c. 3100–332 BCE",
        "Date_Sort": "-3100",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Egyptian",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Egyptian Djed Pillar – Backbone of Osiris / Vertical Energy Column",
        "Person_Visionary": "Osirian cult; pharaonic tradition",
        "Location": "Memphis / Abydos / Heliopolis (Egypt)",
        "Source_Text": "Pyramid Texts c. 2400 BCE; Book of the Dead; Djed raising ceremony; Clark 'Myth and Symbol in Ancient Egypt' (1959)",
        "Description": "The Djed pillar (Dd) = 'stability; backbone of Osiris'; raised annually in the Djed ceremony at Memphis; represents the spinal column of the cosmic god Osiris; four horizontal bands (vertebrae/stacked rings); raises the deceased to immortality; vertical axis linking earth to heaven. The Djed as structural parallel to the sushumna nadi (central channel) and stupa spire — the ritual raising of the Djed spine IS the Egyptian equivalent of kundalini activation.",
        "Key_Motifs": "Djed pillar; Osiris backbone; four horizontal bands; stability; immortality; vertical axis; raising ceremony",
        "Parallel_Systems": "Kundalini (Djed = backbone/spine = sushumna; four bands as proto-chakra levels – Tier C); Hekhalot (vertical axis linking realms = seven-hall vertical axis); OT Visions (Moses' brazen serpent Nehushtan; brazen pillar)",
        "Scholarly_Source": "Clark 'Myth and Symbol in Ancient Egypt' (1959) pp. 239–243; Budge 'Osiris and the Egyptian Resurrection' (1911); Reymond 'The Mythical Origin of the Egyptian Temple' (1969)",
        "Evidence_Tier": "B",
        "Notes": "Djed as kundalini spine is Tier C for the causal parallel; Djed as axis mundi / immortality symbol is Tier A in Egyptian context; four bands as proto-chakra markers is Tier C",
    },
    {
        "Date_Label": "c. 3000–1500 BCE",
        "Date_Sort": "-3000",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Egyptian",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Egyptian Nine Body-Souls (Ka / Ba / Akh / Sahu / Sekhem) – Subtle Body System",
        "Person_Visionary": "Egyptian funerary tradition",
        "Location": "Heliopolis / Memphis / Thebes (Egypt)",
        "Source_Text": "Pyramid Texts; Coffin Texts; Book of the Dead; Assmann 'Death and Salvation in Ancient Egypt' (Cornell UP 2005)",
        "Description": "Egyptian nine-body system: Khat (physical body); Ka (vital double = prana/life-force); Ba (individual soul-bird that ascends; personal divine faculty); Akh (luminous transfigured spirit = goal of transformation); Sahu (spiritual body); Sekhem (power-body); Ren (true name); Ib (heart-soul); Khaibit (shadow). System of ascending transformation from physical to luminous body: Ka=prana; Ba=individual soul; Akh=enlightened luminous state = sahasrara parallel. Most sophisticated ancient subtle-body system outside India.",
        "Key_Motifs": "Ka (vital double/prana); Ba (soul-bird ascent); Akh (luminous spirit); Sahu (spiritual body); nine body-souls; ascending transformation; luminous goal",
        "Parallel_Systems": "Kundalini (Ka=prana; Akh=luminous awakening at sahasrara – Tier B); Hekhalot (Enoch/Metatron transformation into luminous angelic form = Akh process – Tier A parallel); Meditation Timeline",
        "Scholarly_Source": "Assmann 'Death and Salvation in Ancient Egypt' (Cornell UP 2005); Hornung 'Conceptions of God in Ancient Egypt' (1982); Quirke 'Ancient Egyptian Religion' (1992)",
        "Evidence_Tier": "B",
        "Notes": "Nine Egyptian body-souls = most sophisticated ancient subtle-body system outside India; Ka-prana and Akh-sahasrara parallels are Tier B; nine bodies vs. seven chakras requires caution in cross-cultural comparison",
    },
    # ── Five Elements / Tattvas / Stupa ───────────────────────────────────────────
    {
        "Date_Label": "c. 1500–500 BCE",
        "Date_Sort": "-1500",
        "Tradition_System": "Kundalini/Subtle Body",
        "Sub_Tradition": "Vedic (Five Elements / Tattvas)",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Pancha Mahabhutas + Five Tattva Geometric Shapes – Foundations of Kundalini and Stupa Design",
        "Person_Visionary": "Vedic rishis; codified in Samkhya and Tantric traditions",
        "Location": "Northern India",
        "Source_Text": "Taittiriya Upanishad 2.1–5; Samkhya Karika; Tantric tattva texts; Rigveda (Mahabhuta proto-references)",
        "Description": "The five primordial elements (Pancha Mahabhutas) are paired with five geometric tattva shapes: (1) PRITHVI/Earth = yellow square = muladhara chakra = solidity; (2) APAS/Water = silver crescent = svadhisthana = fluidity; (3) AGNI/Fire = red upward triangle = manipura = transformation; (4) VAYU/Air = blue circle = anahata = movement; (5) AKASHA/Space = black bindu point or egg = vishuddha = pure vibration/sound. These five shapes simultaneously define: (a) the five lower chakras; (b) the five architectural levels of the stupa; (c) the Vedic cosmological elements; (d) the system of tactile/visual tattva meditation for kundalini activation. Direct structural parallel to Plato's five regular solids in the Timaeus.",
        "Key_Motifs": "Yellow square (earth/muladhara); silver crescent (water/svadhisthana); red triangle (fire/manipura); blue circle (air/anahata); black bindu point (space/vishuddha); five geometric forms; chakra correspondence",
        "Parallel_Systems": "Kundalini (each tattva governs a specific chakra; tattva visualization = primary kundalini activation technique); Stupa design (five tattva shapes = five stupa architectural levels – CRITICAL link); Platonic Solids (Plato's five regular solids = Greek parallel to the same five-element geometry); Hekhalot (five-element material world = substrate of lower Sefirotic levels)",
        "Scholarly_Source": "Feuerstein 'The Yoga Tradition' (1998) pp. 108–114; Avalon/Woodroffe 'The Serpent Power' (1919) ch. 3; Zimmer 'Myths and Symbols in Indian Art and Civilization' (1946); Taittiriya Upanishad 2.1–5",
        "Evidence_Tier": "A",
        "Notes": "THE foundational Vedic subtle-body / cosmic-element system; every subsequent kundalini and stupa system builds on this five-shape framework; tattva geometric forms attested in Tantric iconography from c. 800 CE onward but philosophical basis is Vedic; structural parallel to Platonic five solids is Tier A; causal link is Tier B–C",
    },
    {
        "Date_Label": "c. 500–100 BCE",
        "Date_Sort": "-400",
        "Tradition_System": "Kundalini/Subtle Body",
        "Sub_Tradition": "Buddhist / Vedic Architectural",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Stupa as Verticalized Five-Element Cosmos – Pancha Dhatu Architecture (Snodgrass)",
        "Person_Visionary": "Ashoka and subsequent Buddhist traditions; architects",
        "Location": "India (Sanchi; Amaravati; Bharhut); later Tibet; Java; Sri Lanka",
        "Source_Text": "Drimed Namnyiy (Tibetan canonical stupa symbolism); Snodgrass 'The Symbolism of the Stupa' (Cornell SEAP 1985)",
        "Description": "The stupa IS the five Vedic elements and five tattva shapes stacked vertically as a complete cosmology and subtle body: (1) SQUARE BASE = Prithvi/Earth = yellow = muladhara = foundation; (2) SPHERICAL DOME (anda) = Apas/Water = white = cosmic egg/womb = svadhisthana; (3) TRIANGULAR/CONICAL HARMIKA SPIRE = Agni/Fire = red = transformation = manipura; (4) CRESCENT CANOPY = Vayu/Air = blue = liberation = anahata; (5) CIRCULAR FINIAL / BINDU POINT = Akasha/Space = pure consciousness = vishuddha/sahasrara. The entire stupa = an externalized meditating Buddha's body; the Buddha's relics inside = inner fire of enlightenment; circumambulation (pradakshina) = activating the energy body around the central axis.",
        "Key_Motifs": "Square base (earth/muladhara); dome/anda (water/svadhisthana); spire/harmika (fire/manipura); crescent canopy (air/anahata); apex bindu (space/sahasrara); five elements stacked; cosmic egg; relics = inner fire; circumambulation = energy activation",
        "Parallel_Systems": "Kundalini (stupa = exteriorized five-chakra body; five levels = five lower chakras; finial = sahasrara – Tier B); Vedic Mahabhutas (direct application of tattva system); Platonic Solids (same five-element hierarchy from earth-cube to aether-point); Mesopotamian Tree (stupa = Buddhist tree-of-life equivalent; axis mundi function identical)",
        "Scholarly_Source": "Snodgrass 'The Symbolism of the Stupa' (Cornell SEAP 1985) – definitive; Beer 'The Handbook of Tibetan Buddhist Symbols' (2003) ch. 4; Zimmer 'Myths and Symbols in Indian Art and Civilization' (1946) pp. 140–162; Coomaraswamy 'The Origin of the Buddha Image' (1927)",
        "Evidence_Tier": "A",
        "Notes": "Snodgrass (1985) is the authoritative source establishing stupa-as-five-elements; the five-tattva-shape architectural system is unambiguously documented (Tier A); the kundalini-stupa parallel is Tier B and discussed in modern comparative scholarship",
    },
    {
        "Date_Label": "c. 300–100 BCE",
        "Date_Sort": "-200",
        "Tradition_System": "Kundalini/Subtle Body",
        "Sub_Tradition": "Buddhist Tantric",
        "Entry_Type": "Comparative Note",
        "Title_Event": "Stupa Yasti (Inner Axis Pillar) and Chattravali (Ring Spire) – Buddhist Subtle-Body Column",
        "Person_Visionary": "Buddhist Tantric tradition",
        "Location": "India / Tibet / Central Asia",
        "Source_Text": "Snodgrass 'The Symbolism of the Stupa' (1985) pp. 295–310; Beer 'Handbook of Tibetan Buddhist Symbols' (2003)",
        "Description": "The stupa's central pillar (yasti = 'life-tree') runs from foundation to apex through the dome; above the dome rises the chattravali: a stack of rings/discs (13 in Tibetan tradition = 13 stages to enlightenment: 10 bhumi + 3 special states); the inner axis pillar = sushumna; the rings = the chakra column; circumambulation mimics kundalini circling the central channel; the entire stupa IS a three-dimensional visualization of the subtle body standing upright with spine extended. Yasti = sushumna; chattravali = chakras ascending to the crown bindu.",
        "Key_Motifs": "Yasti (inner axis pillar = sushumna); chattravali (13 rings = chakra/bhumi column); circumambulation; bhumi stages; inner life-tree; three-dimensional subtle body visualization",
        "Parallel_Systems": "Kundalini (yasti = sushumna; chattravali rings = chakra column – Tier B; most direct architectural kundalini parallel); Hekhalot (13-stage ascent parallel to seven halls); Five Elements (stupa lower five = tattvas; upper rings = stages beyond material elements)",
        "Scholarly_Source": "Snodgrass 'The Symbolism of the Stupa' (1985) pp. 295–310; Beer 'The Handbook of Tibetan Buddhist Symbols' (2003) pp. 215–225",
        "Evidence_Tier": "B",
        "Notes": "Yasti/chattravali as subtle body column documented in Tibetan canonical texts (Tier A for Buddhist meaning); 13 rings = specific bhumi stages (Tier A); kundalini-spine parallel is Tier B",
    },
    # ── Zoroastrian / Avestan ─────────────────────────────────────────────────────
    {
        "Date_Label": "c. 1000–700 BCE",
        "Date_Sort": "-900",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Iranian / Avestan",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Haoma Tree / Gaokerena – Zoroastrian Cosmic Axis (Post-Assyrian System per Parpola)",
        "Person_Visionary": "Zarathustra / Zoroastrian tradition",
        "Location": "Eastern Iran (Airyana Vaejah / Bactria)",
        "Source_Text": "Avesta: Yasna 9–11 (Haoma hymns); Vendidad; Bundahishn; Boyce 'A History of Zoroastrianism' vol. 1 (1975)",
        "Description": "White Haoma tree (Gaokerena) grows in the Vourakasha sea at the center of the world; the Saena/Simurgh bird nests at the crown; eating Haoma grants immortality and resurrection; cosmic axis connecting heaven and earth; a second tree (Asha-sp = 'tree of all seeds') disperses all plants; the serpent of Ahriman (evil) attacks the root but is repelled by the kar-fish. Structurally identical to the Assyrian Tree (eagle at top; serpent at root; cosmic sea; immortality function) and Norse Yggdrasil. Parpola identifies Zoroastrianism as a direct post-Assyrian outgrowth of the Tree theology.",
        "Key_Motifs": "White Haoma tree; Vourakasha cosmic sea; Saena/Simurgh at crown; serpent at root; immortality; cosmic axis; seeds of all plants; kar-fish protector",
        "Parallel_Systems": "Mesopotamian Tree (Haoma = direct parallel to Eridu kigkanu in cosmic sea; both grant immortality – Tier A structural connection); OT Visions (Eden Tree of Life); Kundalini (Haoma ritual = ecstatic pranic awakening – Tier C); Norse Yggdrasil (eagle-crown/serpent-root = identical three-world motif); Steppe World Tree",
        "Scholarly_Source": "Boyce 'A History of Zoroastrianism' vol. 1 (1975) pp. 156–160; Gnoli 'Zoroaster's Time and Homeland' (1980); Parpola JNES 52/3 (1993) p. 189 (Zoroastrianism as post-Assyrian outgrowth)",
        "Evidence_Tier": "A",
        "Notes": "Haoma tree = white axis mundi with Simurgh (eagle) at crown and serpent at root = structurally identical to pan-Eurasian world-tree pattern; haoma/soma ritual = earliest documented entheogenic-ecstatic tradition in Eurasia; Parpola places Zoroastrianism as direct post-Assyrian outgrowth",
    },
    # ── Greek (Pythagorean / Platonic) ────────────────────────────────────────────
    {
        "Date_Label": "c. 570–350 BCE",
        "Date_Sort": "-540",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Greek (Pythagorean / Platonic)",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Pythagorean Tetractys and Plato's Five Regular Solids – Mathematical Tree of Life and Greek Tattva System",
        "Person_Visionary": "Pythagoras (c. 570–495 BCE); Plato (428–348 BCE)",
        "Location": "Samos / Croton / Athens",
        "Source_Text": "Pythagorean sources via Iamblichus; Plato 'Timaeus' 53c–56c; Parpola JNES 52/3 (1993) pp. 186–188 and Excursus 3 pp. 205–208",
        "Description": "Pythagorean tetractys (1+2+3+4=10; triangular arrangement of 10 points) encodes the same mathematical structure as the Assyrian Tree's 10 divine-number positions. Pythagoras spent years in Babylon learning from the Magi (ancient testimony). Plato's Timaeus assigns five regular solids to the five elements: CUBE=Earth; ICOSAHEDRON=Water; TETRAHEDRON=Fire; OCTAHEDRON=Air; DODECAHEDRON=Aether — exactly parallel to Vedic Pancha Mahabhutas with their five tattva shapes (square; crescent; triangle; circle; bindu point). Parpola argues Pythagoreanism, Orphism, and Platonism all emerged simultaneously from Assyrian intellectual collapse (c. 612 BCE).",
        "Key_Motifs": "Tetractys (10 points = 10 nodes); Monad; five regular solids (cube/icosahedron/tetrahedron/octahedron/dodecahedron); five elements; Pythagorean sacred numbers = Mesopotamian divine numbers",
        "Parallel_Systems": "Kundalini (Platonic five solids = Greek tattva-shape equivalent: cube=earth=muladhara; tetrahedron=fire=manipura etc. – Tier B; structural parallel to Vedic five tattvas is Tier A); Kabbalah (Sefer Yetzirah structures ten Sefirot as Pythagorean ten numbers); Vedic Mahabhutas (parallel five-element geometry); Stupa (same earth-to-aether hierarchy)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) pp. 186–188; O'Meara 'Pythagoras Revived' (OUP 1989) p. 27; Cornford 'Plato's Cosmology' (1937) pp. 210–239; Burkert 'Lore and Science in Ancient Pythagoreanism' (1972)",
        "Evidence_Tier": "B",
        "Notes": "Parpola identifies Pythagoreanism as post-Assyrian system; 10-point tetractys = 10-node Tree diagram is his mathematical proof; Platonic five solids = Greek codification of five-element geometry; structural parallel to Vedic tattvas is Tier A; causal link is Tier B–C",
    },
    # ── Harappan ──────────────────────────────────────────────────────────────────
    {
        "Date_Label": "c. 2400–1900 BCE",
        "Date_Sort": "-2400",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Harappan / Indus Valley",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Harappan Sacred Fig Tree (Asvattha / Pipal) – Proto-Bodhi Tree and Inverted Cosmic Tree",
        "Person_Visionary": "Unknown Indus Valley civilization",
        "Location": "Mohenjo-daro / Harappa / Dholavira (Indus Valley)",
        "Source_Text": "Harappan pottery and glyptic c. 2400 BCE; Parpola JNES 52/3 (1993) p. 162 n. 1 and p. 191 n. 109; Kepinski (1982)",
        "Description": "Harappan sacred tree forms (attested in pottery, glyptic, Indus script since 2400 BCE) display Proto-Elamite and Akkadian influence; Parpola: 'basic doctrines of the Tree had already spread to India by the early third millennium BCE via Proto-Elamite intermediaries.' The Harappan sacred tree is the fig/pipal tree (asvattha / Ficus religiosa = Bodhi tree) = the same inverted tree of the Upanishads and Bhagavad Gita (roots above; branches below). This is NOT derived from the late Assyrian Tree but represents an earlier stage reaching India independently. Buddha's enlightenment under the pipal tree directly inherits this Harappan tradition.",
        "Key_Motifs": "Harappan fig tree / pipal (asvattha); Proto-Elamite influence; inverted cosmic tree (roots above; branches below); 2400 BCE attestation; Bodhi tree precursor; Bhagavad Gita inverted tree",
        "Parallel_Systems": "Vedic/Kundalini (asvattha = Bodhi tree = Tree of Enlightenment; Buddha's enlightenment inherits Harappan sacred tree – Tier A); Mesopotamian Tree (shared 3rd-millennium Elamite intermediary per Parpola); Stupa (dome = cosmic egg = Harappan pipal dome association)",
        "Scholarly_Source": "Parpola JNES 52/3 (1993) p. 162 n. 1; Mackay 'Further Excavations at Mohenjo-daro' (1938); Possehl 'The Indus Civilization: A Contemporary Perspective' (2002)",
        "Evidence_Tier": "A",
        "Notes": "Harappan pipal/fig tree = one of the most common Harappan seal motifs (Tier A); identification as Vedic asvattha / Bodhi tree is Tier A; Proto-Elamite transmission vector is Tier B; possibly the oldest documented 'tree of enlightenment' motif",
    },
    # ── Scythian / Steppe ─────────────────────────────────────────────────────────
    {
        "Date_Label": "c. 1200–500 BCE",
        "Date_Sort": "-1000",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Scythian / Eurasian Steppe",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Scythian / Steppe World Tree – Eagle at Crown; Serpent at Root; Shamanic Cosmic Axis",
        "Person_Visionary": "Scythian; Saka; and related steppe cultures",
        "Location": "Pontic Steppe / Central Asia (Ukraine through Kazakhstan to Altai Mountains)",
        "Source_Text": "Scythian metalwork (Pazyryk; Kul Oba; Tolstaya Mogila); Rolle 'The World of the Scythians' (1989); Anthony 'The Horse the Wheel and Language' (2007)",
        "Description": "Steppe world tree attested across Eurasia from Black Sea to Mongolia: tree with eagle at crown; serpent/dragon at root; antithetical flanking animals (stags; horses; griffins); tree as cosmic axis connecting shamanic upper/middle/lower worlds; shaman ascends the world tree in trance; eagle = upper-world divine messenger; serpent = chthonic power. In Saka/Scythian art the eagle-serpent battle is one of the defining iconographic themes — directly parallel to Garuda-Naga in Indian tradition. Structurally identical to Mesopotamian sacred tree and Zoroastrian Gaokerena.",
        "Key_Motifs": "World tree; eagle at crown; serpent/dragon at root; flanking animals; shamanic three-world ascent; axis mundi; eagle-serpent battle; pan-Eurasian PIE substrate",
        "Parallel_Systems": "Mesopotamian Tree (direct iconographic parallel; Scythians in contact with Assyria from 8th c. BCE – Tier B); Hekhalot (shamanic ascent through levels = Merkabah mysticism same structure); Kundalini (eagle-crown = sahasrara; serpent-root = muladhara kundalini – Tier C); Zoroastrian (Saena/Simurgh in Gaokerena = same eagle-in-tree); Norse Yggdrasil (identical eagle/serpent structure confirming PIE substrate)",
        "Scholarly_Source": "Rolle 'The World of the Scythians' (University of California Press 1989); Anthony 'The Horse the Wheel and Language' (2007); Eliade 'Shamanism: Archaic Techniques of Ecstasy' (1964) ch. 8",
        "Evidence_Tier": "A",
        "Notes": "Steppe world tree is pan-Eurasian and predates most textual traditions; eagle-crown / serpent-root polarity is the defining pan-Eurasian world-tree structure; confirms Proto-Indo-European substrate for the motif",
    },
    # ── Norse ─────────────────────────────────────────────────────────────────────
    {
        "Date_Label": "c. 1000–1220 CE",
        "Date_Sort": "1100",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Norse / Germanic",
        "Entry_Type": "Comparative Entry",
        "Title_Event": "Yggdrasil – Norse Cosmic Tree; Odin's Nine-Night Self-Sacrifice; Nine Worlds",
        "Person_Visionary": "Norse tradition; codified in Prose Edda (Snorri Sturluson c. 1220 CE)",
        "Location": "Iceland / Scandinavia",
        "Source_Text": "Prose Edda (Gylfaginning ch. 15–16); Poetic Edda (Völuspá); Davidson 'Gods and Myths of Northern Europe' (1964)",
        "Description": "Yggdrasil (Odin's gallows-tree / 'steed of the Terrible One') = cosmic ash connecting nine worlds; three roots reach to: Asgard (Urðarbrunnr well of fate); Jotunheim (Mimir's well of wisdom); Niflheim (Hvergelmir spring with dragon Niðhöggr gnawing the root). Eagle at crown; Niðhöggr at root; squirrel Ratatoskr carries messages up and down. Odin hangs for nine nights to gain the runes (esoteric knowledge through voluntary ordeal on the world-axis). Mimir's well of wisdom at the root = Ea's Apsu as wisdom-ocean (Mesopotamian structural parallel per Parpola).",
        "Key_Motifs": "Nine worlds; three roots; eagle at crown; Niðhöggr serpent at root; Odin nine-night ordeal; runes as gained esoteric knowledge; Mimir's well of wisdom",
        "Parallel_Systems": "Steppe World Tree (structurally identical eagle/serpent polarity – PIE shared substrate); Mesopotamian Tree (Mimir's well = Ea's Apsu wisdom-ocean; Odin hanging = king-as-Tree mystical ordeal); Kundalini (Odin's nine-night ordeal on tree = tapas/kundalini activation through sustained suffering – Tier C); Hekhalot (runes as passwords obtained through divine ordeal – Tier C)",
        "Scholarly_Source": "Davidson 'Gods and Myths of Northern Europe' (Penguin 1964); Simek 'Dictionary of Northern Mythology' (1993); Turville-Petre 'Myth and Religion of the North' (1964)",
        "Evidence_Tier": "B",
        "Notes": "Yggdrasil is the most complete world-tree system in European tradition; eagle-serpent polarity confirms pan-Eurasian PIE pattern; Odin hanging = world-axis self-sacrifice shares theology with crucified Christ and Osiris-in-tree",
    },
    # ── Daoist ────────────────────────────────────────────────────────────────────
    {
        "Date_Label": "c. 300 BCE–200 CE",
        "Date_Sort": "-200",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Daoist / Chinese",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Daoist Microcosmic Orbit (Xiao Zhoutian) – Chinese Kundalini Equivalent",
        "Person_Visionary": "Daoist inner alchemy (neidan) tradition; Yellow Emperor tradition",
        "Location": "China (Han Dynasty and onward)",
        "Source_Text": "Huang Di Nei Jing (c. 300–100 BCE); 'The Secret of the Golden Flower' (Taiyi Jinhua Zongzhi); Ge Hong 'Baopuzi' (c. 320 CE); Cleary tr. (1991)",
        "Description": "Microcosmic orbit (small heavenly circulation = Xiao Zhoutian): qi circulates through two primary channels: (1) Du Mai (Governing Vessel) = ascending along spine from tailbone (Huiyin) to crown (Baihui) = structurally equivalent to sushumna/kundalini rising; (2) Ren Mai (Conception Vessel) = descending from crown down front to perineum = completing the circuit. Three dan tian (cinnabar fields) as energy centers: lower dan tian (belly/navel) = muladhara equivalent; middle dan tian (heart) = anahata equivalent; upper dan tian (crown/third eye) = sahasrara equivalent. 'Return to the source' = union with Dao = kundalini reaching the crown.",
        "Key_Motifs": "Du Mai (spine-ascending = sushumna); Ren Mai (front-descending = circuit completion); three dan tian (lower/middle/upper = three chakra zones); qi circulation; inner alchemy; return to source",
        "Parallel_Systems": "Kundalini (Du Mai = sushumna; three dan tian = lower-middle-upper chakra zones; microcosmic orbit = kundalini body-circuit – Tier A for structural parallel; independent development); Hekhalot (ascending channel to the divine = same vertical ascent motif); Stupa (three dan tian = three main stupa architectural levels)",
        "Scholarly_Source": "Cleary 'The Secret of the Golden Flower' (1991); Despeux 'Taoisme et corps humain' (1994); Needham 'Science and Civilisation in China' vol. 5 pt. 5 (1983)",
        "Evidence_Tier": "B",
        "Notes": "Du Mai/Ren Mai circuit = most structurally direct non-Indian parallel to kundalini; three dan tian = three-zone chakra system; independent development is Tier A; causal connection to Indian system is Tier C",
    },
    # ── Canaanite / Asherah ───────────────────────────────────────────────────────
    {
        "Date_Label": "c. 1200–600 BCE",
        "Date_Sort": "-1001",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Canaanite / Ugaritic",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Asherah – Sacred Tree / Serpent Goddess as Living Energy Axis in Israelite Religion",
        "Person_Visionary": "Asherah cult; Canaanite tradition; Israelite religion (before Deuteronomistic reform)",
        "Location": "Canaan / Ugarit / Israel (Syro-Palestinian region)",
        "Source_Text": "Ugaritic texts KTU 1.1–6; 1 Kgs 14:23; 2 Kgs 17:10; Dt 16:21; Hadley 'The Cult of Asherah in Ancient Israel and Judah' (Cambridge UP 2000)",
        "Description": "Asherah = Canaanite mother goddess symbolized by a wooden pole or stylized tree (asherah); often depicted as a nude figure with snakes and flanking animals; the asherah pole stood beside Yahweh's altar in the Jerusalem Temple until the 7th c. BCE Deuteronomistic reform; Lady of the Sea; mother of 70 gods; her tree = axis connecting heaven and earth. Her serpent association links her to Egyptian Wadjet and Babylonian Ishtar/Tiamat = she IS the Sefirah Tiferet/Ishtar on Parpola's Mesopotamian Tree diagram. Her suppression by Deuteronomistic reformers = the erasure of the sacred tree / feminine from Israelite religion that Hekhalot mysticism arguably seeks to recover through the Shekhinah.",
        "Key_Motifs": "Asherah pole (sacred tree); nude goddess; flanking animals; serpent association; Lady of the Sea; mother of 70 gods; prohibited in Deuteronomistic reform; Shekhinah as continuation",
        "Parallel_Systems": "OT Visions (Asherah's suppression is the backdrop to Hekhalot's recovery of Shekhinah as feminine divine presence – Tier B); Mesopotamian Tree (Asherah = Canaanite form of Babylonian Ishtar = Tiferet on Parpola's diagram – Tier B); Kundalini (Asherah as Shakti goddess = divine feminine energy axis – Tier C)",
        "Scholarly_Source": "Hadley 'The Cult of Asherah in Ancient Israel and Judah' (Cambridge UP 2000); Smith 'The Early History of God' 2nd ed. (2002) ch. 4; Dever 'Did God Have a Wife?' (2005)",
        "Evidence_Tier": "A",
        "Notes": "Asherah pole = one of the best-documented sacred objects in biblical archaeology (Tier A); identification with Babylonian Ishtar/Tiferet on Parpola's Tree is Tier B; the Asherah→Shekhinah continuity in Jewish mysticism is a major scholarly discussion (Tier B)",
    },
    # ── Mandaean ─────────────────────────────────────────────────────────────────
    {
        "Date_Label": "c. 150 BCE–400 CE",
        "Date_Sort": "-50",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Gnostic / Mandaean",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Mandaean Lightworld Ascent – Seven Sky-Gates / Password-Guarded Heavens / Living Water Column",
        "Person_Visionary": "Mandaean tradition (Nasoreai priests; John the Baptist community)",
        "Location": "Lower Mesopotamia / southern Iraq and Iran (Aramaic-speaking)",
        "Source_Text": "Ginza Rba (The Great Treasure; Lidzbarski ed. 1925); Mandaean Book of the Zodiac; Buckley 'The Mandaeans: Ancient Texts and Modern People' (AOS 2002)",
        "Description": "Mandaean system: soul ascends through seven planetary heavens (matharthas) back to the Lightworld (Alma d-Nhura); each heaven guarded by Uthra (angelic beings) requiring passwords; soul must demonstrate purity; the Lightworld = source of living water and divine light; John the Baptist revered as prophet; baptism (masbuta) in flowing water = repeated ritual of ascent/purification; the light-column (stauros = pillar of light) = axis of return. Structurally the closest geographic and theological parallel to Hekhalot outside Jewish tradition — both are Mesopotamian-area systems with seven-heaven/seven-hall angelic gatekeeping and password requirements.",
        "Key_Motifs": "Seven planetary heavens; password-guarded angelic gates; Uthra; Lightworld; living water; light-pillar (stauros); John the Baptist; baptism as repeated ascent",
        "Parallel_Systems": "Hekhalot (seven heavens with angelic gatekeepers requiring passwords = structural twin of seven Hekhalot halls – Tier A parallel); OT Visions (John the Baptist tradition; NT heavenly visions); Kundalini (light-pillar/stauros = subtle body central channel – Tier C)",
        "Scholarly_Source": "Buckley 'The Mandaeans: Ancient Texts and Modern People' (AOS 2002); Drower 'The Mandaeans of Iraq and Iran' (1937); Scholem 'Jewish Gnosticism, Merkabah Mysticism' (1960) pp. 44–56",
        "Evidence_Tier": "A",
        "Notes": "Mandaean system is the closest geographic and structural parallel to Hekhalot outside Jewish tradition; direct Hekhalot influence OR common Babylonian source both plausible; the password-guarding structure is strikingly specific and unlikely to be coincidental",
    },
    # ── Hermetic / Caduceus ───────────────────────────────────────────────────────
    {
        "Date_Label": "c. 200 BCE–400 CE",
        "Date_Sort": "-100",
        "Tradition_System": "Eurasian Precursor",
        "Sub_Tradition": "Greco-Egyptian (Hermetic)",
        "Entry_Type": "Origin Marker",
        "Title_Event": "Caduceus – Hermetic Serpent-Staff as Western Kundalini Diagram (Ida / Pingala / Sushumna)",
        "Person_Visionary": "Hermes Trismegistus (revealed tradition); Greek-Egyptian synthesis",
        "Location": "Alexandria / Egypt (Greco-Roman period)",
        "Source_Text": "Corpus Hermeticum (Nock & Festugière ed. 1945); Homeric Hymn to Hermes; healing-serpent-staff-and-pillar.csv; Parpola JNES 52/3 (1993) n. 68",
        "Description": "The caduceus (kerykeion) = Hermes's staff with two intertwined serpents topped by wings; the two serpents = polar opposites (ida/pingala; active/passive; sun/moon; mercy/judgment); the central staff = sushumna = Pillar of Equilibrium on the Kabbalistic Tree; the wings at top = sahasrara / crown / Keter; the intertwining creates the exact ida-pingala pattern of kundalini physiology. The caduceus appears as a healing and psychopomp symbol — guide of souls = same function as the angelus interpres in Hekhalot (angelic guide at each hall). In Parpola's diagram Hermes = Nabu/Mercury = Netzah (Victory/Messenger) on the divine tree; apkallu figures holding pine cones = same position on the Assyrian Tree.",
        "Key_Motifs": "Two intertwined serpents (ida/pingala); central staff (sushumna); wings at top (sahasrara/Keter); psychopomp function; healing; polar opposites unified on central axis; Nabu-Hermes = Netzah",
        "Parallel_Systems": "Kundalini (caduceus = Western kundalini diagram: two serpents = ida/pingala; staff = sushumna; wings = sahasrara – Tier B; structural parallel widely accepted in comparative mysticism); Hekhalot (Metatron/Hermes as angelic guide-of-souls parallel); Mesopotamian Tree (apkallu with pine cone = Nabu-Hermes position on Parpola's Tree); OT Visions (Moses' brazen serpent Nehushtan = staff-with-serpent precursor)",
        "Scholarly_Source": "Kingsley 'Ancient Philosophy Mystery and Magic: Empedocles and Pythagorean Tradition' (OUP 1995); healing-serpent-staff-and-pillar.csv; Parpola JNES 52/3 (1993) n. 68",
        "Evidence_Tier": "B",
        "Notes": "Caduceus-as-kundalini is the standard comparative mysticism argument (Tier B); structural parallel visually undeniable; functional psychopomp-angelus interpres parallel strengthens the case; causal connection between Greek and Indian systems unproven",
    },
]

# Read existing headers
with open(PATH, encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    existing = list(reader)

print(f"Existing rows: {len(existing)}")
print(f"Fieldnames: {fieldnames}")

# Append new rows
with open(PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL, extrasaction='ignore')
    for row in NEW_ROWS:
        writer.writerow(row)

# Verify
with open(PATH, encoding='utf-8') as f:
    reader = csv.DictReader(f)
    all_rows = list(reader)

from collections import Counter
print(f"\nTotal rows after append: {len(all_rows)}")
trad = Counter(r['Tradition_System'] for r in all_rows)
print("Tradition breakdown:")
for t, c in sorted(trad.items()):
    print(f"  {t}: {c}")
sorts = [int(r['Date_Sort']) for r in all_rows if r.get('Date_Sort','').lstrip('-').isdigit()]
sorts.sort()
print(f"Date range: {sorts[0]} to {sorts[-1]}")
