#!/usr/bin/env python3
"""
Replace [GPT ERROR] strings in hellenic/ai-enabled-list.csv with real content.
Teacher column sourced from Diogenes Laërtius, Stanford Encyclopedia of Philosophy,
and standard classical reference works.

Run from project root:
    python3 scripts/fix_greek_phil.py
"""

import csv
from pathlib import Path

TARGET = Path("static/sources/hellenic/ai-enabled-list.csv")
GPT_ERR = '[GPT ERROR] Error: The model "gpt-3.5-turbo" is disabled in this space.'

# Map: Name (as it appears in col 0) → (teacher, notes_override_or_None)
# notes_override only used when the Notes cell also contained a GPT error
DATA: dict[str, tuple[str, str | None]] = {
    # --- Platonists (rows 2–102) ---
    "Aedesia":                       ("Hermias (husband); influenced by Syrianus", None),
    "Aedesius":                      ("Iamblichus Chalcidensis", None),
    "Aeneas of Gaza":                ("Hierocles of Alexandria", None),
    "Aeschines of Neapolis":         ("Carneades of Carnea", None),
    "Agapius":                       ("Marinus of Neapolis", None),
    "Albinus":                       ("Gaius the Platonist (attributed)", None),
    "Alcinous":                      ("", None),
    "Ambrosius Theodosius Macrobius": ("", None),
    "Amelius":                       ("Plotinus", None),
    "Ammonius Hermiae":              ("Proclus Lycaeus", None),
    "Ammonius of Athens":            ("", None),
    "Antiochus of Ascalon":          ("Philo of Larissa; also Mnesarchus", None),
    "Antoninus":                     ("Sosipatra of Ephesus (mother)", None),
    "Apuleius":                      ("Gaius the Platonist (attributed)", None),
    "Arcesilaus":                    ("Crantor; Polemon", None),
    "Aristonymus":                   ("Plato", None),
    "Asclepigenia":                  ("Plutarch of Athens (father)", None),
    "Asclepiodotus of Alexandria":   ("Proclus Lycaeus", None),
    "Atticus":                       ("", None),
    "Augustine of Hippo":            ("Ambrose of Milan; influenced by Plotinus and Porphyry",
                                      "Bishop of Hippo; synthesised Neoplatonism with Christian theology; author of Confessions and The City of God"),
    "Axiothea of Phlius":            ("Plato", None),
    "Boethius":                      ("influenced by Ammonius Hermiae and Aristotelian commentators",
                                      "Roman statesman and philosopher; author of The Consolation of Philosophy; executed under Theodoric"),
    "Calippus of Syracuse":          ("Plato; Eudoxus of Cnidus",
                                      "Athenian astronomer and mathematician; improved on Eudoxus' planetary model"),
    "Carneades of Carnea":           ("Hegesinus of Pergamon; Diogenes of Babylon",
                                      "Head of the New Academy; famous for arguing both sides of a case in Rome (155 BC)"),
    "Cassius Longinus":              ("Ammonius Saccos; Origen the Pagan",
                                      "Third-century rhetorician and philosopher; adviser to Queen Zenobia of Palmyra"),
    "Chaeron of Pellene":            ("Plato",
                                      "Became tyrant of Pellene after studying with Plato"),
    "Charmadas":                     ("Carneades of Carnea",
                                      "Shared leadership of the Academy with Clitomachus and Aeschines around 110 BC"),
    "Chrysanthius of Sardis":        ("Aedesius",
                                      "Refused Julian's invitation to Antioch; remained in Sardis"),
    "Clement of Alexandria":         ("Pantaenus",
                                      "Head of the Catechetical School of Alexandria; synthesised Platonism and Christianity"),
    "Clitomachus":                   ("Carneades of Carnea",
                                      "Carthaginian-born head of the New Academy; prolific author, none of whose works survive"),
    "Coriscus of Scepsis":           ("Plato", None),
    "Crantor":                       ("Xenocrates of Chalcedon; Polemon",
                                      "First known commentator on Plato's Timaeus"),
    "Crates of Athens":              ("Polemon",
                                      "Scholarch of the Old Academy after Polemon"),
    "Damascius":                     ("Isidore of Alexandria; Marinus of Neapolis",
                                      "Last head of the Platonic Academy before Justinian's closure in 529 AD"),
    "Demetrius of Amphipolis":       ("Plato", None),
    "Dexippus":                      ("Iamblichus Chalcidensis", None),
    "Dio of Alexandria":             ("Philo of Larissa", None),
    "Diocles of Cnidus":             ("", None),
    "Diodorus of Adramyttium":       ("Philo of Larissa", None),
    "Domninus of Larissa":           ("Syrianus", None),
    "Erastus of Scepsis":            ("Plato", None),
    "Euaeon of Lampsacus":           ("Plato", None),
    "Eudoxus of Cnidus":             ("Plato; Archytas of Tarentum", None),
    "Eusebius of Myndus":            ("Aedesius", None),
    "Eustathius of Cappadocia":      ("Aedesius; Sosipatra", None),
    "Evander":                       ("Lacydes of Cyrene", None),
    "Gaius the Platonist":           ("", None),
    "Hagnon of Tarsus":              ("Carneades of Carnea", None),
    "Hegesinus of Pergamon":         ("Evander", None),
    "Hegias":                        ("Proclus Lycaeus", None),
    "Heliodorus of Alexandria":      ("Ammonius Hermiae (father)", None),
    "Heraclides of Aenus":           ("Plato", None),
    "Heraclides Ponticus":           ("Plato; Speusippus", None),
    "Hermias":                       ("Syrianus", None),
    "Hermodorus of Syracuse":        ("Plato", None),
    "Hestiaeus of Perinthus":        ("Plato", None),
    "Hierius":                       ("Proclus Lycaeus", None),
    "Hierocles of Alexandria":       ("Plutarch of Athens", None),
    "Hypatia of Alexandria":         ("Theon of Alexandria (father)", None),
    "Iamblichus Chalcidensis":       ("Anatolius of Laodicea; Porphyry of Tyre", None),
    "Isidore of Alexandria":         ("Proclus Lycaeus; Marinus of Neapolis", None),
    "Lacydes of Cyrene":             ("Arcesilaus", None),
    "Lastheneia of Mantinea":        ("Plato", None),
    "Marinus of Neapolis":           ("Proclus Lycaeus", None),
    "Maximus of Ephesus":            ("Aedesius", None),
    "Maximus of Tyre":               ("", None),
    "Menedemus of Pyrrha":           ("Plato", None),
    "Metrodorus of Stratonicea":     ("Carneades of Carnea", None),
    "Numenius of Apamea":            ("", None),
    "Nymphidianus of Smyrna":        ("Aedesius", None),
    "Olympiodorus the Younger":      ("Ammonius Hermiae", None),
    "Onasander":                     ("", None),
    "Origen":                        ("Ammonius Saccos; Pantaenus", None),
    "Origen the Pagan":              ("Ammonius Saccos", None),
    "Philip of Opus":                ("Plato", None),
    "Philo of Alexandria":           ("", None),
    "Philo of Larissa":              ("Clitomachus", None),
    "Plato":                         ("Socrates; Cratylus; Pythagoreanism (influence)", None),
    "Plotinus":                      ("Ammonius Saccos", None),
    "Plutarch":                      ("Ammonius of Athens", None),
    "Plutarch of Athens":            ("Syrianus (student); taught by own father", None),
    "Polemon":                       ("Xenocrates of Chalcedon", None),
    "Porphyry of Tyre":              ("Plotinus; Longinus", None),
    "Priscian of Lydia":             ("Damascius; Simplicius", None),
    "Priscus of Epirus":             ("Aedesius", None),
    "Proclus Lycaeus":               ("Plutarch of Athens; Syrianus", None),
    "Pseudo-Dionysius the Areopagite": ("influenced by Proclus Lycaeus (writings)", None),
    "Python of Aenus":               ("Plato", None),
    "Simplicius of Cilicia":         ("Ammonius Hermiae; Damascius", None),
    "Sopater of Apamea":             ("Iamblichus Chalcidensis", None),
    "Sosipatra of Ephesus":          ("Chaldean sages (tradition); Aedesius (husband)", None),
    "Speusippus":                    ("Plato (also nephew)", None),
    "Synesius":                      ("Hypatia of Alexandria", None),
    "Syrianus":                      ("Plutarch of Athens", None),
    "Telecles of Phocis":            ("Lacydes of Cyrene", None),
    "Theodorus of Asine":            ("Porphyry of Tyre; Iamblichus Chalcidensis", None),
    "Timaeus the Sophist":           ("", None),
    "Timolaus of Cyzicus":           ("Plato", None),
    "Xenocrates of Chalcedon":       ("Plato", None),
    "Zenodotus":                     ("Proclus Lycaeus", None),
    # --- Second batch (rows 103+) ---
    "Ammonius Saccas":               ("", "Alexandrian philosopher; teacher of Plotinus and Origen the Pagan; founder of Neoplatonism; left no writings"),
    "Aristarchus of Samos":          ("Strato of Lampsacus (attributed)",
                                      "First known model placing the Sun at the centre of the known universe with the Earth revolving around it"),
    "Damo":                          ("Pythagoras (father)",
                                      "Reportedly the daughter of Pythagoras and Theano; entrusted with his writings"),
    "Epicurus":                      ("Nausiphanes; Pamphilus",
                                      "Said that the purpose of philosophy was to attain tranquility characterised by ataraxia (freedom from anxiety) and aponia (freedom from pain)"),
    "Zeno of Sidon":                 ("Apollodorus the Epicurean",
                                      "Sometimes termed the 'leading Epicurean'; Cicero attended his lectures"),
    "Basilides the Epicurean":       ("Dionysius of Lamptrai",
                                      "Succeeded Dionysius of Lamptrai as head of the Epicurean school at Athens"),
    "Porphyry":                      ("Plotinus; Longinus",
                                      "Taught by Plotinus; wrote the Isagoge, an introduction to Aristotle's Categories; edited the Enneads"),
    "Epictetus":                     ("Musonius Rufus",
                                      "Wrote the Enchiridion (compiled by Arrian), a handbook of Stoic ethical advice; born a slave in Hierapolis"),
    "Dionysius the Renegade":        ("Zeno of Citium; Heraclides Ponticus",
                                      "Abandoned Stoicism for Cyrenaicism after suffering severe eye pain; called 'the Turncoat'"),
    "Heraclitus":                    ("",
                                      "Called 'the Obscure'; claimed 'You cannot step in the same river twice' and identified logos as the governing principle of the cosmos; held all things are fire"),
    "Xenophanes of Colophon":        ("",
                                      "Claimed that if oxen were able to imagine gods, those gods would be in the image of oxen; critiqued anthropomorphic religion"),
    "Socrates":                      ("Archelaus; Diotima of Mantinea (tradition); Prodicus",
                                      "Considered one of the founders of Western philosophy; credited as being the first moral philosopher; executed 399 BC"),
    "Pyrrho":                        ("Bryson of Achaea; Anaxarchus (companion of Alexander)",
                                      "Credited as being the first sceptic philosopher; encountered Indian gymnosophists on Alexander's campaign"),
    "Basilides (Stoic)":             ("Chrysippus", None),
    "Zeno of Elea":                  ("Parmenides of Elea",
                                      "Famous creator of Zeno's paradoxes, arguing against plurality and motion"),
    "Thales":                        ("",
                                      "First philosopher; held that the first principle (arche) is water; one of the Seven Sages of Greece; predicted the solar eclipse of 585 BC"),
    "Zenobius":                      ("", None),
    "Aristotle":                     ("Plato",
                                      "Founder of the Peripatetic school; student of Plato; tutor of Alexander the Great; wrote foundational works in logic, biology, ethics, politics, and metaphysics"),
    "Zeno of Citium":                ("Crates of Thebes; Stilpo; Polemon; Diodorus Cronus",
                                      "Founder of the Stoic school of philosophy; taught in the Stoa Poikile (Painted Porch) in Athens"),
    "Xenophilus":                    ("",
                                      "Friend and teacher of Aristoxenus; lived to over 105 years according to ancient sources"),
    "Parmenides of Elea":            ("Xenophanes of Colophon (attributed)",
                                      "Held that the only thing that exists is Being itself, and that change and plurality are illusions; teacher of Zeno of Elea"),
    "Bion of Borysthenes":           ("Crates of Thebes; Theodorus the Atheist; Theophrastus",
                                      "Once was a slave; later freed and became a wandering Cynic-influenced philosopher"),
    "Dardanus of Athens":            ("Panaetius",
                                      "One of several leaders of the Stoa after the death of Panaetius"),
    "Phaedo of Elis":                ("Socrates",
                                      "Originally founded the School of Elis; it was later transferred to Eretria by his pupil Menedemus"),
    "Acrion":                        ("", None),
    "Adrastus of Aphrodisias":       ("Aspasius (attributed)", None),
    "Aenesidemus":                   ("",
                                      "Wrote Pyrrhonist Discourses, a central text for the Pyrrhonists; revived Pyrrhonism in the 1st century BC"),
    "Aesara":                        ("",
                                      "Wrote On Human Nature, of which a fragment is preserved by Stobaeus; argued the soul has three parts"),
    "Aeschines of Sphettus":         ("Socrates",
                                      "Part of Socrates' circle and likely present at his death; wrote dialogues featuring Socrates"),
    "Aetius":                        ("", None),
    "Agathobulus":                   ("",
                                      "Known for his severe asceticism; teacher of Demonax and Peregrinus Proteus"),
    "Agathosthenes":                 ("",
                                      "Referred to by Tzetzes as his authority in matters connected with geography"),
    "Agrippa the Skeptic":           ("",
                                      "Thought to be the creator of the 'five grounds of doubt' (Agrippa's trilemma)"),
    "Alcibiades":                    ("Socrates",
                                      "Athenian general and politician; ward of Pericles; notoriously shifted allegiances between Athens, Sparta, and Persia"),
    "Alcmaeon of Croton":            ("Pythagoras (attributed)",
                                      "Interested in medicine; possibly the first to distinguish veins from arteries"),
    "Alexamenus of Teos":            ("Socrates (attributed)",
                                      "May have been the first to write philosophical dialogues, predating Plato"),
    "Alexander of Aegae":            ("",
                                      "Tutored the emperor Nero"),
    "Alexander of Aphrodisias":      ("Sosigenes (attributed)",
                                      "Influential commentator on the Corpus Aristotelicum; called 'the Exegete'"),
    "Alexicrates":                   ("", None),
    "Alexinus":                      ("Eubulides",
                                      "Founded his own school which did not fare well; known for eristic arguments against Stoics"),
    "Anaxagoras":                    ("Anaximenes (attributed)",
                                      "Proposed that the sun is a fiery stone; introduced nous (mind) as the ordering principle of the cosmos; teacher of Pericles and Euripides"),
    "Anaxarchus":                    ("Democritus (school)",
                                      "Companion of Alexander the Great; known for equanimity in the face of pain"),
    "Anaxilaus":                     ("", None),
    "Anaximander":                   ("Thales",
                                      "First philosopher known to write in prose; proposed the apeiron (the indefinite) as the first principle"),
    "Anaximenes of Miletus":         ("Anaximander",
                                      "Held that air is the primary substance underlying all things"),
    "Androcydes":                    ("", None),
    "Andronicus of Rhodes":          ("",
                                      "Edited and organised Aristotle's works into the corpus still read today; coined the term 'metaphysics'"),
    "Anniceris":                     ("Aristippus (school)",
                                      "Modified Cyrenaic hedonism to allow for altruistic pleasure; redeemed Plato from slavery in Aegina"),
    "Antipater of Cyrene":           ("Aristippus", None),
    "Antipater of Tarsus":           ("Diogenes of Babylon", None),
    "Antipater of Tyre":             ("Panaetius", None),
    "Antisthenes":                   ("Socrates; Gorgias",
                                      "Founder of Cynicism; held virtue alone is sufficient for happiness and that it cannot be taught, only demonstrated"),
    "Apollodorus of Athens":         ("Diogenes of Babylon", None),
    "Apollodorus of Seleucia":       ("Diogenes of Babylon", None),
    "Apollodorus the Epicurean":     ("Zeno of Sidon (school)", None),
    "Apollonius Cronus":             ("Eubulides", None),
    "Apollonius of Tyana":           ("Euxenus of Heracleia", None),
    "Apollonius of Tyre":            ("Panaetius", None),
    "Archedemus of Tarsus":          ("Diogenes of Babylon", None),
    "Archelaus":                     ("Anaxagoras", None),
    "Archytas":                      ("Philolaus", None),
    "Arete of Cyrene":               ("Aristippus (father)",
                                      "Daughter and student of Aristippus; mother and teacher of Aristippus the Younger; wrote 40 books according to Diogenes Laërtius"),
    "Arignote":                      ("Pythagoras (attributed father or teacher)", None),
    "Aristippus":                    ("Socrates; Protagoras (early influence)", None),
    "Aristippus the Younger":        ("Arete of Cyrene (mother)", None),
    "Aristo of Alexandria":          ("", None),
    "Aristo of Ceos":                ("Lyco of Troas", None),
    "Aristo of Chios":               ("Zeno of Citium; Polemon", None),
    "Aristoclea":                    ("", None),
    "Aristocles of Messene":         ("", None),
    "Aristocreon":                   ("Chrysippus (nephew)", None),
    "Aristotle of Cyrene":           ("Aristippus (school)", None),
    "Aristotle of Mytilene":         ("", None),
    "Aristoxenus":                   ("Aristotle; Xenophilus (Pythagorean)", None),
    "Arius Didymus":                 ("", None),
    "Asclepiades of Phlius":         ("Stilpo; Menedemus", None),
    "Asclepiades the Cynic":         ("", None),
    "Aspasius":                      ("", None),
    "Athenaeus of Seleucia":         ("", None),
    "Athenodoros Cananites":         ("Posidonius", None),
    "Athenodoros Cordylion":         ("", None),
    "Athenodorus of Soli":           ("", None),
    "Attalus":                       ("Athenodoros Cananites (attributed)", None),
    "Batis of Lampsacus":            ("Epicurus (inner circle)", None),
    "Boethus of Sidon":              ("Andronicus of Rhodes", None),
    "Boethus of Sidon (Stoic)":      ("Diogenes of Babylon", None),
    "Bolus of Mendes":               ("", None),
    "Brontinus":                     ("Pythagoras", None),
    "Bryson of Achaea":              ("Stilpo; Clinomachus", None),
    "Callicles":                     ("", None),
    "Calliphon":                     ("", None),
    "Calliphon of Croton":           ("Pythagoras", None),
    "Callistratus":                  ("", None),
    "Carneiscus":                    ("Epicurus", None),
    "Cebes":                         ("Philolaus; then Socrates", None),
    "Celsus":                        ("Albinus or a Platonist", None),
    "Cercidas":                      ("Diogenes of Sinope (Cynic influence)", None),
    "Cercops":                       ("Pythagoras", None),
    "Chaerephon":                    ("Socrates", None),
    "Chamaeleon":                    ("Aristotle (attributed)", None),
    "Chrysanthius":                  ("Aedesius", None),
    "Chrysippus":                    ("Cleanthes; Zeno of Citium",
                                      "Third head of the Stoic school; prolific systematiser of Stoic logic and ethics; said 'If Chrysippus had not existed, there would be no Stoa'"),
    "Cleanthes":                     ("Zeno of Citium",
                                      "Second head of the Stoic school; author of the Hymn to Zeus; succeeded Zeno as scholarch"),
    "Clearchus of Soli":             ("Aristotle", None),
    "Cleinias of Tarentum":          ("Archytas (attributed)", None),
    "Cleomedes":                     ("", None),
    "Cleomenes":                     ("", None),
    "Clinomachus":                   ("Euclid of Megara", None),
    "Colotes":                       ("Epicurus", None),
    "Crates of Mallus":              ("", None),
    "Crates of Thebes":              ("Diogenes of Sinope", None),
    "Cratippus of Pergamon":         ("", None),
    "Cratylus":                      ("Heraclitus", None),
    "Crescens the Cynic":            ("", None),
    "Crinis":                        ("Chrysippus (school)", None),
    "Critolaus":                     ("", None),
    "Cronius":                       ("Numenius of Apamea", None),
    "Damis":                         ("Apollonius of Tyana", None),
    "Demetrius Lacon":               ("Protarchus of Bargylia", None),
    "Demetrius Phalereus":           ("Theophrastus", None),
    "Demetrius the Cynic":           ("", None),
    "Democrates":                    ("", None),
    "Democritus":                    ("Leucippus",
                                      "Co-founder of the atomic theory; held that everything is composed of indivisible atoms in the void"),
    "Demonax":                       ("Agathobulus; then Epictetus (influence)", None),
    "Diagoras of Melos":             ("Democritus (influence)",
                                      "Known as 'Diagoras the Atheist'; allegedly denied the existence of the gods"),
    "Dicaearchus":                   ("Aristotle", None),
    "Dio Chrysostom":                ("Musonius Rufus", None),
    "Diodorus Cronus":               ("Apollonius Cronus", None),
    "Diodorus of Aspendus":          ("", None),
    "Diodorus of Tyre":              ("Critolaus", None),
    "Diodotus":                      ("", None),
    "Diogenes of Apollonia":         ("Anaximenes (influence)", None),
    "Diogenes of Babylon":           ("Chrysippus", None),
    "Diogenes of Oenoanda":          ("", None),
    "Diogenes of Seleucia":          ("", None),
    "Diogenes of Sinope":            ("Antisthenes", None),
    "Diogenes of Tarsus":            ("", None),
    "Dionysius of Chalcedon":        ("Clinomachus", None),
    "Dionysius of Cyrene":           ("", None),
    "Dionysius of Lamptrai":         ("Zeno of Sidon", None),
    "Diotima of Mantinea":           ("", None),
    "Diotimus":                      ("", None),
    "Echecrates":                    ("Philolaus; Eurytus", None),
    "Ecphantus":                     ("Hicetas", None),
    "Empedocles":                    ("Pythagoras (tradition); Parmenides (influence)", None),
    "Epicharmus of Kos":             ("Pythagoras", None),
    "Eubulides":                     ("Euclid of Megara", None),
    "Euclid of Megara":              ("Socrates", None),
    "Eudemus of Rhodes":             ("Aristotle", None),
    "Eudorus of Alexandria":         ("", None),
    "Euenus":                        ("", None),
    "Euphantus":                     ("Eubulides", None),
    "Euphraeus":                     ("Plato", None),
    "Euphrates":                     ("Musonius Rufus", None),
    "Eurytus":                       ("Philolaus", None),
    "Favorinus":                     ("Dio Chrysostom; Plutarch", None),
    "Geminus":                       ("Posidonius", None),
    "Gorgias":                       ("Empedocles; Tisias", None),
    "Hecataeus of Abdera":           ("Pyrrho (influence)", None),
    "Hecato of Rhodes":              ("Panaetius", None),
    "Hegesias of Cyrene":            ("Aristippus (school)", None),
    "Heraclides Lembus":             ("", None),
    "Heraclius":                     ("", None),
    "Herillus of Carthage":          ("Zeno of Citium", None),
    "Hermagoras of Amphipolis":      ("", None),
    "Hermarchus":                    ("Epicurus", None),
    "Herminus":                      ("", None),
    "Hermippus of Smyrna":           ("", None),
    "Hermotimus of Clazomenae":      ("", None),
    "Hicetas":                       ("Philolaus (school)", None),
    "Hierocles (Stoic)":             ("", None),
    "Hieronymus of Rhodes":          ("", None),
    "Himerius":                      ("", None),
    "Hipparchia of Maroneia":        ("Crates of Thebes (husband and teacher)", None),
    "Hippasus":                      ("Pythagoras", None),
    "Hippias":                       ("", None),
    "Hippo":                         ("", None),
    "Horus":                         ("", None),
    "Ichthyas":                      ("Euclid of Megara", None),
    "Idomeneus of Lampsacus":        ("Epicurus", None),
    "Ion of Chios":                  ("", None),
    "Jason of Nysa":                 ("Posidonius", None),
    "Leonteus of Lampsacus":         ("Epicurus", None),
    "Leontion":                      ("Epicurus", None),
    "Leucippus":                     ("Parmenides; Zeno of Elea (influence)", None),
    "Lyco of Iasos":                 ("", None),
    "Lyco of Troas":                 ("Strato of Lampsacus", None),
    "Lycophron":                     ("Gorgias", None),
    "Lysis of Taras":                ("Pythagoras", None),
    "Meleager of Gadara":            ("", None),
    "Melissus of Samos":             ("Parmenides", None),
    "Menedemus":                     ("Phaedo of Elis; Stilpo", None),
    "Menedemus the Cynic":           ("", None),
    "Menippus":                      ("Crates of Thebes", None),
    "Metrocles":                     ("Crates of Thebes (brother-in-law)", None),
    "Metrodorus of Athens":          ("", None),
    "Metrodorus of Chios":           ("Democritus", None),
    "Metrodorus of Cos":             ("", None),
    "Metrodorus of Lampsacus (the elder)": ("Anaxagoras", None),
    "Metrodorus of Lampsacus (the younger)": ("Epicurus", None),
    "Mnesarchus of Athens":          ("Panaetius", None),
    "Moderatus of Gades":            ("", None),
    "Monimus":                       ("Diogenes of Sinope", None),
    "Myia":                          ("Pythagoras (father)", None),
    "Nausiphanes":                   ("Democritus; Pyrrho", None),
    "Nicarete of Megara":            ("Stilpo", None),
    "Nicolaus of Damascus":          ("", None),
    "Nicomachus":                    ("", None),
    "Nicomachus (son of Aristotle)": ("Aristotle (father)", None),
    "Ocellus Lucanus":               ("Pythagoras (school)", None),
    "Oenomaus of Gadara":            ("", None),
    "Olympiodorus the Elder":        ("", None),
    "Onatas":                        ("", None),
    "Panaetius":                     ("Diogenes of Babylon; Crates of Mallus; Antipater of Tarsus", None),
    "Pancrates of Athens":           ("", None),
    "Panthoides":                    ("Eubulides", None),
    "Pasicles of Thebes":            ("Euclid of Megara", None),
    "Patro the Epicurean":           ("", None),
    "Peregrinus Proteus":            ("Agathobulus", None),
    "Persaeus":                      ("Zeno of Citium", None),
    "Phaedrus":                      ("Epicurus; Philo of Larissa (lectures attended)", None),
    "Phanias of Eresus":             ("Aristotle", None),
    "Phanto of Phlius":              ("", None),
    "Philiscus of Aegina":           ("Diogenes of Sinope", None),
    "Philiscus of Thessaly":         ("", None),
    "Philo":                         ("", None),
    "Philo the Dialectician":        ("Diodorus Cronus", None),
    "Philodemus":                    ("Zeno of Sidon", None),
    "Philolaus":                     ("Pythagoras (school)", None),
    "Philonides of Laodicea":        ("Diogenes of Babylon", None),
    "Philostratus":                  ("", None),
    "Phintys":                       ("Pythagoras (school)", None),
    "Polemarchus":                   ("", None),
    "Polemon of Athens":             ("Xenocrates of Chalcedon", None),
    "Polemon of Laodicea":           ("", None),
    "Polus":                         ("Gorgias", None),
    "Polyaenus of Lampsacus":        ("Epicurus", None),
    "Polystratus":                   ("Hermarchus", None),
    "Posidonius":                    ("Panaetius", None),
    "Potamo of Alexandria":          ("", None),
    "Praxiphanes":                   ("Theophrastus", None),
    "Proclus Mallotes":              ("", None),
    "Proclus of Laodicea":           ("", None),
    "Prodicus":                      ("", None),
    "Protagoras":                    ("Democritus (attributed)", None),
    "Ptolemy-el-Garib":              ("", None),
    "Pythagoras":                    ("Pherecydes of Syros; Thales (tradition)", None),
    "Sallustius":                    ("Julian the Apostate (patron); influenced by Iamblichus", None),
    "Sallustius of Emesa":           ("", None),
    "Satyrus":                       ("", None),
    "Secundus the Silent":           ("", None),
    "Sextus Empiricus":              ("", None),
    "Sextus of Chaeronea":           ("Plutarch (uncle)", None),
    "Simmias of Thebes":             ("Philolaus; then Socrates", None),
    "Simon the Shoemaker":           ("Socrates", None),
    "Siro":                          ("", None),
    "Sosigenes":                     ("", None),
    "Sotion":                        ("", None),
    "Sphaerus":                      ("Cleanthes; Zeno of Citium", None),
    "Stilpo":                        ("Euclid of Megara; Thrasymachus of Corinth", None),
    "Strato of Lampsacus":           ("Theophrastus", None),
    "Telauges":                      ("Pythagoras (son)", None),
    "Teles the Cynic":               ("", None),
    "Theagenes of Patras":           ("", None),
    "Theano":                        ("Pythagoras (husband)", None),
    "Themista of Lampsacus":         ("Epicurus", None),
    "Themistius":                    ("", None),
    "Theodorus the Atheist":         ("Aristippus the Younger; Anniceris", None),
    "Theon of Smyrna":               ("", None),
    "Theophrastus":                  ("Aristotle", None),
    "Thrasymachus":                  ("", None),
    "Thrasymachus of Corinth":       ("Ichthyas", None),
    "Timaeus of Locri":              ("Pythagoras (attributed)", None),
    "Timon":                         ("Pyrrho", None),
    "Timycha":                       ("Pythagoras (disciple)", None),
    "Tisias":                        ("Corax of Syracuse (attributed)", None),
    "Xenarchus of Seleucia":         ("", None),
    "Xeniades":                      ("", None),
    "Xenophon":                      ("Socrates", None),
    "Zeno of Tarsus":                ("Chrysippus", None),
}


def clean(val: str) -> str:
    return "" if GPT_ERR in val else val


def main():
    with TARGET.open(newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.reader(fh))

    header = rows[0]
    out_rows = [header]

    for row in rows[1:]:
        # Pad to at least 6 cols
        while len(row) < 6:
            row.append("")

        name = row[0].strip()
        teacher_raw = row[2]
        notes_raw   = row[5]

        # Clean GPT error strings
        row[2] = clean(teacher_raw)
        row[5] = clean(notes_raw)

        if name in DATA:
            teacher, notes_override = DATA[name]
            if GPT_ERR in teacher_raw or row[2] == "":
                row[2] = teacher
            if notes_override is not None and (GPT_ERR in notes_raw or row[5] == ""):
                row[5] = notes_override

        out_rows.append(row)

    with TARGET.open("w", newline="", encoding="utf-8") as fh:
        csv.writer(fh).writerows(out_rows)

    gpt_remaining = sum(
        1 for r in out_rows[1:]
        for cell in r if GPT_ERR in cell
    )
    print(f"Written {len(out_rows)-1} rows. GPT error strings remaining: {gpt_remaining}")


if __name__ == "__main__":
    main()
